Repository wecode-bootcamp-korea/44-1st-unicon-backend, pull requests merged in 2023-04, with the labels that each got.

#1 [임성근][ADD]:unicon초기환경셋팅
  .env.sample
  .gitignore
  .prettierrc
  app.js
  middlewares/error.js
  package-lock.json
  package.json
  routes/index.js
Labels: 멘토 리뷰 요청

#3 [김민서][ADD]dbmate
  .gitignore
  db/migrations/20230404062516_create_users_table.sql
  db/migrations/20230404062616_create_product_table.sql
  db/migrations/20230404062646_create_gender_table.sql
  db/migrations/20230404065343_create_product_image_table.sql
  db/migrations/20230404065406_create_product_detail_table.sql
  db/migrations/20230404065430_create_main_category_table.sql
  db/migrations/20230404065448_create_sub_category_table.sql
  db/migrations/20230404070559_create_review_table.sql
  db/migrations/20230404070619_create_cart_table.sql
  db/migrations/20230404070632_create_orders_table.sql
  db/migrations/20230404070654_create_order_item_table.sql
  db/migrations/20230404070715_create_order_status_table.sql
  db/migrations/20230404070724_create_order_item_status_table.sql
Labels: 멘토 리뷰 요청

#4 [김민서][ADD]Feature/product page
  .gitignore
  app.js
  controllers/productController.js
  middlewares/error.js
  models/appDataSource.js
  models/productDao.js
  routes/index.js
  routes/productRouter.js
  services/productService.js
Labels: 수정 요청

#5 [임성근][ADD]: 회원가입, 로그인, 인가 통합 기능 구현
  .gitignore
  app.js
  controllers/userController.js
  middlewares/auth.js
  models/appDataSource.js
  models/userDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/userRouter.js
  services/userService.js
Labels: 멘토 리뷰 요청

#7 [김민서][ADD]Feature/product list
  app.js
  controllers/productController.js
  db/migrations/20230408130919_create_show_room_table.sql
  db/migrations/20230408134953_alter_table_show_room_table.sql
  middlewares/error.js
  models/appDataSource.js
  models/conditionMake.js
  models/productDao.js
  models/userDao.js
  routes/productRouter.js
  services/productService.js
  services/userService.js
Labels: 멘토 리뷰 요청

#16 [김민서][FIX]loginRequired
  middlewares/auth.js
Labels: 멘토 리뷰 요청

#20 [임성근][ADD]: 포인트 업데이트 적용 및 payment transaction 적용
  controllers/paymentController.js
  models/paymentDao.js
  routes/index.js
  routes/paymentRouter.js
  services/paymentService.js
Labels: 멘토 리뷰 요청

#21 [김민서][FIX]is_new
  models/productDao.js
Labels: 멘토 리뷰 요청

#22 [김민서][ADD]purchaseditems
  controllers/orderController.js
  models/orderDao.js
  routes/orderRouter.js
  services/orderService.js
Labels: 멘토 리뷰 요청

#19 [최상현] 버그 수정 에러 핸들링
  controllers/cartController.js
  db/migrations/20230413030643_order_status_insert.sql
  middlewares/enums.js
  models/cartDao.js
  models/orderDao.js
  services/cartService.js
  services/orderService.js
Labels: 멘토 리뷰 요청

#23 최상현 fix/ upateCartList
  controllers/cartController.js
  models/orderDao.js
  services/orderService.js
Labels: 완료

#24 [Modify] Fix/payment
  controllers/paymentController.js
  models/paymentDao.js
Labels: 멘토 리뷰 요청
